name: Deploy to MangoHost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Deploy to MangoHost
        run: |
          ssh -o StrictHostKeyChecking=no root@193.36.38.65 << 'EOF'
          cd /root/utils
          git checkout main
          git fetch origin main
          git reset --hard origin/main
          docker-compose down
          docker-compose up -d --build
          EOF
